// Content lives as JSON in /content and is read-only at runtime. Git is the
// versioning system: every rule change is a commit with a date.
//
// It is *imported* rather than fetched. Under Vite that means a malformed file
// fails the build instead of producing a blank page at 3am.
//
// Books, cards and problems are imported whole: they are small, and every index
// page needs all of them to count anything. Lesson prose is the one thing that
// is not, because there is 966KB of it and a reader who opens one lesson was
// paying for fifty-five. tools/split-content.py cuts it in two:
//
//   catalogue.json    every lesson's metadata — title, timings, section
//                     headings, quiz COUNT. Imported statically below, so
//                     every index, module page and section list still renders
//                     on the first paint with no loading state. That is what
//                     the split is arranged around.
//   module-<id>.json  the section bodies and the quiz questions for one
//                     module, imported on demand by loadLesson/loadModule.
//
// So the synchronous catalogue is still here and still exhaustive; what it no
// longer carries is prose. Only a page that shows a lesson's text or asks its
// questions awaits anything, and only for the module it is in.

import books from '../../content/books.json';

import cardsFoundations from '../../content/cards/foundations.json';
import cardsMethod from '../../content/cards/method.json';
import cardsSubstantive from '../../content/cards/substantive.json';
import cardsGapMethod from '../../content/cards/gap-method-reasoning.json';
import cardsGapProcedure from '../../content/cards/gap-procedure-property.json';
import cardsGapCompany from '../../content/cards/gap-company-evidence-civil.json';

import problemsMethod from '../../content/problems/method.json';
import problemsSubstantive from '../../content/problems/substantive.json';
import problemsAdvanced from '../../content/problems/advanced.json';
import problemsGapMethod from '../../content/problems/gap-method-reasoning.json';
import problemsGapProcedure from '../../content/problems/gap-procedure-property.json';
import problemsGapCompany from '../../content/problems/gap-company-evidence-civil.json';

// Lesson metadata, generated. Regenerated by `npm run content:split`, which
// `predev` and `prebuild` run first, so this is never stale against /content.
import lessonMeta from '../generated/catalogue.json';

// Each new deck is one import above and one entry here.
const DECKS = [cardsFoundations, cardsMethod, cardsSubstantive,
  cardsGapMethod, cardsGapProcedure, cardsGapCompany];

// Problem questions: the reasoning layer. Registered the same way as decks, and
// kept in separate files because they are edited in different sittings from the
// cards — a card is five minutes' work, a problem question is an afternoon.
const PROBLEM_SETS = [problemsMethod, problemsSubstantive, problemsAdvanced,
  problemsGapMethod, problemsGapProcedure, problemsGapCompany];

const cards = DECKS.flatMap(d => d.cards || []);
const problems = PROBLEM_SETS.flatMap(s => s.problems || []);

// Lessons: the exposition, metadata only. The order is the generator's — it is
// not derivable from any field on a lesson, so nothing here re-sorts it.
const lessons = lessonMeta;

const byId = {
  book: index(books.books),
  statute: index(books.statutes),
  module: index(books.modules),
  card: index(cards),
  problem: index(problems),
  lesson: index(lessons),
};

const modules = books.modules.map(m => ({
  ...m,
  cardCount: cards.filter(c => c.moduleId === m.id).length,
  problems: problems.filter(p => p.moduleId === m.id),
  lessons: lessons.filter(l => l.moduleId === m.id),
  books: [...m.primary, ...m.reference].map(id => byId.book[id]).filter(Boolean),
  statuteRefs: m.statutes.map(id => byId.statute[id]).filter(Boolean),
}));

export const catalogue = {
  books: books.books,
  statutes: books.statutes,
  vendors: books.vendors,
  purchasingNotes: books.purchasingNotes,
  modules,
  cards,
  problems,
  lessons,
  // How many quiz questions exist, without any of them. Every page that used to
  // read `quizPool.length` wanted this number and nothing else.
  quizCount: lessons.reduce((n, l) => n + (l.quizCount || 0), 0),
  byId,
  cardTypes: Object.assign({}, ...DECKS.map(d => d.cardTypes || {})),
  bands: PROBLEM_SETS.find(s => s.bands)?.bands || {},
};

function index(rows) {
  return Object.fromEntries((rows || []).map(r => [r.id, r]));
}

// Which illustration plate a lesson gets. A lesson may name its own `plate`;
// otherwise it falls back to one chosen for its module, so a newly written
// lesson is never plateless and never silently gets the generic one.
const PLATE_BY_MODULE = {
  'm-study-method': 'study',
  'm00-foundations': 'pillars',
  'm01-malaysian-legal-system': 'courthouse',
  'm02-legal-research': 'library',
  'm03-constitutional': 'map',
  'm04-criminal-law': 'lamp-blow',
  'm05-criminal-procedure': 'lockup',
  'm06-contract': 'letters',
  'm07-tort': 'scaffold',
  'm08-property': 'register',
  'm09-company': 'company-seal',
  'm10-evidence': 'gate',
  'm11-civil-procedure': 'files',
  'm12-administrative': 'empty-chair',
  'm13-legal-reasoning': 'reasoning',
  'm14-statutory-interpretation': 'statute-page',
};

export function plateFor(lesson) {
  return lesson?.plate || PLATE_BY_MODULE[lesson?.moduleId] || 'statute';
}

export function moduleLabel(m) {
  return m.level === null || m.level === undefined ? '—' : String(m.level);
}

// --- lesson bodies, loaded on demand ---------------------------------------

// Deliberately not `{ eager: true }`: eager would inline all sixteen chunks
// back into the entry bundle and undo the split. Lazy makes Vite emit one
// chunk per module and fetch it the first time something asks for it.
const bodyChunks = import.meta.glob('../generated/module-*.json');

// moduleId → Promise of Map(lessonId → { sections, quiz }). The *promise* is
// cached rather than its value, so two components mounting in the same tick
// share one fetch instead of racing to start two. A failed fetch is evicted:
// an offline blip should not poison the module for the rest of the session.
const bodies = new Map();

function bodiesFor(moduleId) {
  const cached = bodies.get(moduleId);
  if (cached) return cached;
  const load = bodyChunks[`../generated/module-${moduleId}.json`];
  // A module with no lessons has no chunk. That is not an error, and the empty
  // map lets callers merge unconditionally.
  if (!load) return Promise.resolve(new Map());
  const pending = load()
    .then(chunk => new Map((chunk.default || []).map(l => [l.id, l])))
    .catch(err => { bodies.delete(moduleId); throw err; });
  bodies.set(moduleId, pending);
  return pending;
}

/**
 * One lesson, whole: its catalogue metadata with the section bodies and quiz
 * merged in. Null if the id is not a lesson — callers show their own 404, and
 * an unknown id must not fetch a chunk to find that out.
 */
export async function loadLesson(lessonId) {
  const meta = byId.lesson[lessonId];
  if (!meta) return null;
  const body = (await bodiesFor(meta.moduleId)).get(lessonId);
  return { ...meta, ...body };
}

/** Every lesson in one module, whole, in curriculum order. */
export async function loadModule(moduleId) {
  const loaded = await bodiesFor(moduleId);
  return lessons
    .filter(l => l.moduleId === moduleId)
    .map(l => ({ ...l, ...loaded.get(l.id) }));
}

// Every quiz question, tagged with the lesson that asks it. The Arena draws
// from this; a lesson quiz draws from one lesson via loadLesson.
//
// This is the one call that costs all sixteen chunks, which is why it is a
// function and not a constant: nobody pays for it unless they walk into the
// Arena, and after that the chunks are cached like any other module.
let pool = null;

export function loadQuizPool() {
  if (pool) return pool;
  pool = (async () => {
    const ids = [...new Set(lessons.map(l => l.moduleId))];
    const loaded = new Map(await Promise.all(
      ids.map(async id => [id, await bodiesFor(id)])));
    return lessons.flatMap(l =>
      (loaded.get(l.moduleId).get(l.id)?.quiz || []).map(q => ({
        ...q,
        lessonId: l.id,
        lessonTitle: l.title,
        moduleId: l.moduleId,
      })));
  })().catch(err => { pool = null; throw err; });
  return pool;
}

export default catalogue;
